# Generated by Django 2.2.5 on 2019-09-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('atc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_takingoff', to='flight.Flight')),
                ('starting_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tekeoff_atc', to='atc.Atc')),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ending_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_runway', to='atc.Atc')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_landing', to='flight.Flight')),
            ],
        ),
    ]
