# Generated by Django 2.2.5 on 2019-09-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='path',
        ),
    ]
