# Generated by Django 3.0.3 on 2020-02-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_flight_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='height',
        ),
    ]
